### ISSUE TITLE
Telecom doesn't work

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#2]
Relevant nodes:
- rovr_control/mc_to_robot_node
- rovr_control/joy_to_onboard_direct_node
- rovr_control/robot_to_mc_node

Neither onboard joystick nor driver station -> robot control works. Issue 1: The driver station does not properly connect to the robot while on wifi, continuously failing with message "Failed to connect to 192.168.1.19:5554"

Issue 2: The onboard joystick control doesn't work either. No CAN messages are sent.

Issue 2 might affect wifi control as well.

**Comment by juliaschatz** [comment]
Points I've identified so far:
- The telecom nodes talk on different ports than the ones they're given as params. This is a bug with default params. However, they both talk on the same wrong ports so this shouldn't be the issue. It should still be fixed though.
- Why don't we just run the Joy node to connect to the ros master on the robot instead of running it over our own telecom protocol? Not having to deal with networking at all seems like a big pro of using ROS.
- The telecom nodes do use joy_to_onboard_direct so a bug in that re: publishing CAN would affect telecom as well.

**Comment by JWCS** [comment]
Using wifi to connect to ros master is only kinda ok. It's one of the weaker parts of ROS1, in terms of stability and reliability. 
Also, more critically for your use case, y'all get penalized on data transmission. We have no practical control of that using the native ros tool, but y'all can severely improve an control on it through our own explicit sending.

**Comment by juliaschatz** [comment]
We lose 0.02 points per 50 kbits/s, or per 6.25 kbytes/s. If we report joystick data at 20 Hz, this translates to 0.02 points per 39 bytes.

**Comment by juliaschatz** [comment]
My calculation above was incorrect. We lose 1 point per 50 kbit/s, or 1 point per 6.25 kbyte/s

According to `rostopic bw`, the Joy node at a coalesce rate of 0.050 (20 Hz) publishes about 2.5 KByte/s at most- I can get up to 3 KB/s by running my fingers all over the face buttons, and it idles at finger-numbers of bytes/sec if there's no joysticks moving. 2.5 KB/s over the entire match, which is a very high estimate, loses us 0.4 points. 

Reading the current telecom class looks like 6 items. The axes (x4) takes 8 bytes each. The pad and buttons each take 3 bytes each. That's 38 bytes, at 20 Hz, is 760 byte/s which is 0.76 kbyte/s. We would lose 0.12 points. 

A difference of 0.28 points doesn't seem like very much to me when it means using a telecom stack someone else has made and tested vs. our own. This is all so incredibly peanuts compared to other point sources- the many hundred kb/s of cameras, robot mass, amount of material mined.

But I'm curious about what you're saying about ROS nodes over wifi not being stable. Can you tell me about a time you've tried running multiple ROS nodes over wifi and how they failed? Have you proven a custom telecom stack is better?

**Comment by JWCS** [comment]
Actually, the one that was used was tested. It's a UDP (as opposed to a TCP) wrapper on C networking stack. UDP has 1 msg, TCP has a handshake confirmation, which is what ros uses. If you care about not dropping packets, then TCP is better, but if you send (relevant) state over each time, it doesn't matter. 
Nice calcs, good to put a number on it. You can pretty much assume that it will be at a steady rate for the entire match duration; I don't think the data rate should change. 
Now, I'm not saying we will or won't use one stack over the other; to begin with, it's still the beginning of the season. A slight comparison of the two stacks, if it helps you: 
Both are tested. Both are wrappers around lower-level network communication C stack, but on the ROS side it goes one step further and serializes-deserializes ros msg data structures into strings before sending. The complexity of the ROS stack is in configuration, and controlling the data transmission (which messages, which rates); the complexity of this stack is the same: roughly same for configuration, and different for controlling the data transmission. In this, you have to specify a msg spec for sending data, and put data into that spec, at the desired rates (using ros timers). 
The "custom stack" isn't really custom, it's pretty vanilla network programming. The last two years we had made sure to teach interested students about network programming, via Beej's Guide To Network Programming, (which you'd probably love!), so they know how things are really working. 
It doesn't have to be used, but it _is_ a tool; it is easier to do fine-grained control than with the native ros version, more low-level, if you want those features. There's trade-off to both, exactly on that line. 
As for the last question, it's a few things about ros, that I haven't pushed/tested myself, but are known in the community. For example, if you really want to push data over the internet, non-locally, there is a ros/javascript library, specifically for this problem (in terms of scaling). There are projects, especially around the image-transport library, to address sending huge data (specifically image data) over wifi. Additionally, you're probably thinking of what we mentioned about the competition having purposefully, in the past, introduced disturbances in the communication (for teams trying to do autonomous), in which case you might have severe delays between packets. I'm not entirely sure on the last one, but I've heard it before (we've not been good enough (or not get dumped on valentines day)) to experience it ourselves. 
Either way, for local R&D testing, you can simply just use the built-in ros send everything; that's what was done last year. If you want to try making the connection more secure after you're done prototyping and defining your interfaces, I think the ideas behind that telecom stack are the way to go. 

ROS is only now trying, with ROS2, to be industry-grade software all the way down. The ideas behind it are powerful, allowing superb prototyping and development. Like testing an algorithm in matlab instead of C, there are significant benefits to using ros. But, recognize that it also (at least for its current state), that there are areas that could be optimized once solved. For example, you could, after finishing your whole auton stack, completely remove ros and make it monolithic, especially if it's going on a customer/client production machine and not likely to change in current form without going through the whole process again (diff machine/sensors/processing-cabability-into-algo-choice), at which point the process is simple.

**Comment by juliaschatz** [comment]
You've convinced me to step back from completely yeeting the current telecom stack. I still have my issues with it, but for now let's fix the current iteration and then discuss improvements (ideally in conjunction with rewriting the robot structure.

I got rid of some unused-in-current-state versions of the telecom nodes. I left the cmd_vel publishers so we can reference those when we start building subsystems. So far I've also fixed the params in the main_ nodes. There was definitely something wrong there when we were testing before, so maybe teleop will actually work. But other than that, it's very hard to tell what's wrong when converting from Joy messages to canbus messages. I'll push my version of the project to the robot tonight and we'll see if any canbus messages get sent at all when running joy_onboard_direct.

**Comment by JWCS** [comment]
😅 
I hope we're not yeeting anything, most of the stuff has a time and a place for it, an extension to the great big toolbox we call ros, which has itself several (increasingly jank) options for everything. 
On the other hand, we could in theory make some more git-level changes by only having this-years robot specific code in this repo, and other groups of stacks in other repos. That's a separate question. 
Haven't looked at the changes yet, but it was working earlier this year, no changes, which makes this whole darn thing strange. 
Also, there is a benefit to [human interface]_to_canbus msgs: debugging. Testing every step of complexity inevitably reduces problems/stress/errors. I'm just speaking in foresight so as not to in hindsight (like usual).
