### ISSUE TITLE
Filter point clouds to remove arena walls

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#43]
We aren't allowed to use the arena walls to navigate. So these must be removed before the point clouds are removed for navigation. 
The idea is either:
- Find vertical planes and remove them
- Limit the map building to a known area inside the arena so that the walls aren't processed

**Comment by libBAS** [comment]
I think the first option might be better
The walls might end up split into a bunch of planes even if they are flat
So we'll need to be careful about catching/removing them all 
(might not be an issue though, but could be if you do keep small vertical planes as obstacles (but that could be separated from nav))

**Comment by JWCS** [comment]
Technically speaking, in the parameters for move_base, are the params for costmap_2d, which includes the width/height:
- All points that are 'seen' that are outside of the costmap are removed
- Any mis-placed points, due to bad localization, will be updated/cleared given another scan with correct localization.
Ergo, if you just setup the map correctly, it'll automatically "not see the walls".
If you want to be robust, then you filter planes, but that takes more than 3 min of marginal work.

**Comment by juliaschatz** [comment]
Might come back to this later if the laser scan has issues.
